name: Build Executables

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. 1.0.9)'
        required: true
        default: '1.3.2'

permissions:
  contents: write
  actions: write
  packages: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get all tags
          
      - name: Delete existing tag if exists
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/v${{ github.event.inputs.version }}"; then
            git push origin --delete "v${{ github.event.inputs.version }}" || true
            git tag -d "v${{ github.event.inputs.version }}" || true
          fi
          
      - name: Create Tag
        run: |
          git tag "v${{ github.event.inputs.version }}"
          git push origin "v${{ github.event.inputs.version }}"

  build-windows:
    needs: create-tag
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Set version
      shell: bash
      run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build EXE
      run: |
        pyinstaller build.spec
         
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorFocus_${{ env.VERSION }}_windows.exe
        path: dist/CursorFocus_${{ env.VERSION }}_windows.exe

  build-macos-arm64:
    needs: create-tag
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Set version
      shell: bash
      run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build MacOS ARM executable
      run: |
        pyinstaller build.spec
        mv "dist/CursorFocus_${{ env.VERSION }}_mac" "dist/CursorFocus_${{ env.VERSION }}_mac_arm64" || echo "File already has correct name"
        ls -la dist/

    - name: Upload MacOS ARM artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorFocus_${{ env.VERSION }}_mac_arm64
        path: dist/CursorFocus_${{ env.VERSION }}_mac_arm64

  build-linux-x64:
    needs: create-tag
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Set version
      shell: bash
      run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build Linux x64 executable
      env:
        VERSION: ${{ env.VERSION }}
      run: |
        pyinstaller build.spec
        mv "dist/CursorFocus_${{ env.VERSION }}_linux" "dist/CursorFocus_${{ env.VERSION }}_linux_x64" || echo "File already has correct name"
        echo "Contents of dist directory:"
        ls -la dist/
        
    - name: Upload Linux x64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorFocus_${{ env.VERSION }}_linux_x64
        path: dist/CursorFocus_${{ env.VERSION }}_linux_x64


  create-release:
    needs: [build-windows, build-macos-arm64, build-linux-x64]
    runs-on: ubuntu-22.04
    
    steps:
      - name: Get version
        shell: bash
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release files
        run: |
          cd artifacts
          echo "Contents of artifacts directory:"
          ls -la
          echo "Contents of subdirectories:"
          ls -la */
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          files: |
            artifacts/CursorFocus_${{ env.VERSION }}_windows.exe/CursorFocus_${{ env.VERSION }}_windows.exe
            artifacts/CursorFocus_${{ env.VERSION }}_mac_arm64/CursorFocus_${{ env.VERSION }}_mac_arm64
            artifacts/CursorFocus_${{ env.VERSION }}_linux_x64/CursorFocus_${{ env.VERSION }}_linux_x64
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 